version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      gh-action-dependencies:
        applies-to: version-updates
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: monthly
    groups:
      python-workflow-dependencies:
        applies-to: version-updates
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: monthly
    groups:
      docs-dependencies:
        applies-to: version-updates
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: "all"
    groups:
      poetry-dependencies:
        applies-to: version-updates
