version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      gh-action:
        dependency-type: production
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: monthly
    groups:
      python-workflow:
        dependency-type: production
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: monthly
    groups:
      docs:
        dependency-type: production
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: "all"
    groups:
      poetry-prod:
        dependency-type: production
      poetry-dev:
        dependency-type: development
